### ISSUE TITLE
Pq Junit ?

### ISSUE THREAD

**Issue by guizmaii** [tyrcho/path-kata#5]
Pq tu ajoutes Junit comme dépendance et dans tes tests ? Sachant que cela ne sert à rien (sauf si nécessaire pour Maven).

**Comment by tyrcho** [comment]
j'en ai besoin pour l'annotation `@RunWith` qui me permet de lancer les tests depuis Eclipse

**Comment by guizmaii** [comment]
Et avec ScalaIDE (basé sur Eclipse) tu as également besoin de Junit ?

**Comment by tyrcho** [comment]
alors j'ai refait des tests sous ScalaIDE ce soir, on pourrait à la rigueur s'en passer effectivement, mais :
- Infinitest ne fonctionne plus (il ne détecte pas les changements et ne lance plus les tests)
- les vieux baroudeurs comme moi vont chercher un petit moment comment lancer les tests, surtout s'ils sont dans le package par défaut.

Bref, je trouve que le jeu n'en vaut pas la chandelle ...
